* BFI Pre-doctoral Fellows Orientation (Fall 2021)

Welcome to the Bekerman-Friedman Institute! During this orientation we will brief
you in about the tools we believe will help you the most in your RAship at BFI.
We have prepared a set of 1 hour to 1.5 hours sessions about general programming
topics and career and work environment talks. During this orientation you will
interact with both PIs, other pre-doctoral fellows, and current PhD students
that will talk about their careers and their overall experiences as BFI and EPIC
pre-doctoral fellows.

In this repo, you will have all the orientation materials, and some information
related to your first days at EPIC.
   
** Agenda

The orientation will span two weeks. Our main and TA sessions will take place
virtually (Zoom links will be shared later). 

Videos and the agenda can be found [[https://www.dropbox.com/work/RP%20Orientation%202021][here]]
		
** Prerequisites

Before starting this orientation you will need some software first. We will
guide you through the installation process (in Unix-based machines, hopefully).
Also, some of the sessions are assuming some basic knowledge of programming
languages. In general, you are expected to understand object structures (i.e.
lists, dictionaries, matrices, etc.) and some experience in any programming
language.

This is a comprehensive list of what we need to install:

 + ~Git~ (Install [[http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/][command-line tools]] in your MacOS) 
 + Python (3.6+): 
   -Python packages: 
   - ~pandas~ 
   - ~matplotlib~
   - ~ipython~ 
   - ~jupyter~ 
 + R
 + [[https://www.rstudio.com][RStudio]]
 + [[https://www.sublimetext.com][SublimeText]] (or [[https://www.jetbrains.com/pycharm/][PyCharm]] using your educational email) 
 + [If you're working on a server] Vim or if you feel with [[http://www.stallman.org/saint.html][lack of faith]],
   use Emacs. 
   
*** How to install

Although you can install software using click-and-point, you can also install
software in a more programmatic way.

- MacOS users - [[file:./prerequisites/mac_homebrew.md][Instructions]]
- Linux users - You probably know how to do this already
- Windows - Change OS :speak_no_evil:. 

If you have any problem installing any of the software listed, you can always
use [[https://github.com/jdblischak/giladlab-midway-guide][UChicago's Midway]]. 
